import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { demoConnector } from './connectors/demoConnector';
import type { Listing, Tracker } from './types';
import './styles.css';

const STORAGE_KEY='homeholiday-trackers';
const UI_REFRESH_MS=60_000;
type ProviderState={ok:boolean;checkedAt:string;count?:number;message?:string};
type ListingStore={listings:Listing[];refreshedAt:string|null;providerStatus?:Record<string,ProviderState>};
type PropertyGroup={id:string;primary:Listing;sources:Listing[]};
type PriceSort='asc'|'desc'|null;
type ViewMode='cards'|'table';
const PRICE_STEP=5000;
function money(n:number){return new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n)}
function formatDate(value?:string){if(!value)return '—';return new Intl.DateTimeFormat('it-IT').format(new Date(`${value.slice(0,10)}T00:00:00Z`));}
function formatRefresh(value:string|null){if(!value)return 'Dati demo';const date=new Date(value);return Number.isNaN(date.getTime())?'Aggiornamento disponibile':new Intl.DateTimeFormat('it-IT',{dateStyle:'short',timeStyle:'short'}).format(date)}
function loadTrackers():Tracker[]{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return []}}
function providerLabel(value:string){return ({casa:'Casa.it',idealista:'Idealista',subito:'Subito.it',bakeca:'Bakeca.it','immobiliare-public':'Immobiliare.it',immobiliare:'Immobiliare.it',bootstrap:'Bootstrap iniziale'} as Record<string,string>)[value]||value}
function choosePrimary(items:Listing[]){return [...items].sort((a,b)=>{const ar=a.status==='REMOVED'?1:0,br=b.status==='REMOVED'?1:0;if(ar!==br)return ar-br;return ((b.sqm?1:0)+(b.rooms?1:0)+(b.publishedAt?1:0))-((a.sqm?1:0)+(a.rooms?1:0)+(a.publishedAt?1:0))})[0]}
function groupListings(items:Listing[]):PropertyGroup[]{const buckets=new Map<string,Listing[]>();for(const item of items){const key=item.duplicateGroupId||`single:${item.id}`;buckets.set(key,[...(buckets.get(key)||[]),item])}return [...buckets.entries()].map(([id,sources])=>({id,primary:choosePrimary(sources),sources})).sort((a,b)=>new Date(b.primary.firstSeenAt).getTime()-new Date(a.primary.firstSeenAt).getTime())}
async function loadListingStore():Promise<ListingStore>{const response=await fetch(`${import.meta.env.BASE_URL}data/listings.json?v=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error(`Listing store unavailable: ${response.status}`);const data=await response.json() as Partial<ListingStore>;return {listings:Array.isArray(data.listings)?data.listings:[],refreshedAt:typeof data.refreshedAt==='string'?data.refreshedAt:null,providerStatus:data.providerStatus||{}}}
function parseBakeca(html:string,minPrice:number,maxPrice:number):Listing[]{const doc=new DOMParser().parseFromString(html,'text/html');const anchors=[...doc.querySelectorAll<HTMLAnchorElement>('a[href]')].filter(a=>/bakeca\.it\/dettaglio\//i.test(a.href)||/\/annunci\/.*\.html/i.test(a.getAttribute('href')||''));const now=new Date().toISOString();const seen=new Set<string>();const out:Listing[]=[];for(const a of anchors){const card=a.closest('article,li,[class*=item],[class*=result],[class*=annuncio]')||a.parentElement;const text=(card?.textContent||a.textContent||'').replace(/\s+/g,' ').trim();const pm=text.match(/(?:€|EUR)\s*([\d.]+(?:,\d{1,2})?)/i)||text.match(/([\d.]+)\s*€/);if(!pm)continue;const price=Number(pm[1].replace(/\./g,'').replace(',','.'));if(!price||price<minPrice||price>maxPrice)continue;const href=a.href;if(seen.has(href))continue;seen.add(href);const sqmMatch=text.match(/(\d{2,4})\s*m(?:²|2|q)/i);const roomsMatch=text.match(/(\d+)\s*(?:locali|vani)/i);const externalId=(href.match(/(\d{5,})/)||[])[1]||btoa(unescape(encodeURIComponent(href))).slice(-18);out.push({id:`bakeca-device:${externalId}`,externalId,title:(a.textContent||text.slice(0,100)||'Annuncio Bakeca').trim(),location:'Bardonecchia',price,firstSeenAt:now,lastSeenAt:now,sellerType:/privato/i.test(text)?'Privato':'Agenzia',source:'Bakeca.it',sourceUrl:href,sqm:sqmMatch?Number(sqmMatch[1]):undefined,rooms:roomsMatch?Number(roomsMatch[1]):undefined,status:'ACTIVE',priceHistory:[{price,capturedAt:now}]})}return out}
function App(){const [place,setPlace]=useState('Bardonecchia'),[min,setMin]=useState(100000),[max,setMax]=useState(350000),[seller,setSeller]=useState<'Tutti'|'Privato'|'Agenzia'>('Tutti'),[listings,setListings]=useState<Listing[]>([]),[trackers,setTrackers]=useState<Tracker[]>(loadTrackers),[loading,setLoading]=useState(true),[dataSource,setDataSource]=useState<'live'|'demo'>('demo'),[refreshedAt,setRefreshedAt]=useState<string|null>(null),[providerStatus,setProviderStatus]=useState<Record<string,ProviderState>>({}),[deviceRefresh,setDeviceRefresh]=useState(''),[priceSort,setPriceSort]=useState<PriceSort>(null),[viewMode,setViewMode]=useState<ViewMode>('cards');
useEffect(()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(trackers))},[trackers]);useEffect(()=>{let active=true,initial=true;async function refresh(){try{const store=await loadListingStore();if(!active)return;setProviderStatus(store.providerStatus||{});if(store.listings.length){setListings(prev=>{const local=prev.filter(x=>x.id.startsWith('bakeca-device:'));return [...store.listings,...local.filter(l=>!store.listings.some(s=>s.sourceUrl===l.sourceUrl))]});setRefreshedAt(store.refreshedAt);setDataSource('live');setLoading(false);initial=false;return}if(initial){const demo=await demoConnector.search({location:'',minPrice:0,maxPrice:Number.MAX_SAFE_INTEGER});if(active)setListings(demo)}}catch{if(initial){const demo=await demoConnector.search({location:'',minPrice:0,maxPrice:Number.MAX_SAFE_INTEGER});if(active)setListings(demo)}}finally{setLoading(false);initial=false}}void refresh();const timer=window.setInterval(()=>void refresh(),UI_REFRESH_MS);return()=>{active=false;window.clearInterval(timer)}},[]);
const filtered=useMemo(()=>listings.filter(x=>(!place.trim()||x.location.toLowerCase().includes(place.trim().toLowerCase()))&&x.price>=min&&x.price<=max&&(seller==='Tutti'||x.sellerType===seller)),[listings,place,min,max,seller]),properties=useMemo(()=>groupListings(filtered),[filtered]),orderedProperties=useMemo(()=>priceSort?[...properties].sort((a,b)=>priceSort==='asc'?a.primary.price-b.primary.price:b.primary.price-a.primary.price):properties,[properties,priceSort]),visibleProviderStatus=useMemo(()=>{const visible={...providerStatus};const sourceCounts=listings.reduce<Record<string,number>>((counts,item)=>{counts[item.source]=(counts[item.source]??0)+1;return counts},{});const immobiliareCount=sourceCounts['Immobiliare.it']??0;if(immobiliareCount&&!visible['immobiliare-public']&&!visible.immobiliare)visible['immobiliare-public']={ok:true,checkedAt:refreshedAt??'',count:immobiliareCount,message:'Dati disponibili dal bootstrap'};if(visible.bootstrap){const bootstrapSources=['Casa.it','Immobiliare.it'].filter(source=>sourceCounts[source]).map(source=>`${source} (${sourceCounts[source]})`).join(', ');if(bootstrapSources)visible.bootstrap={...visible.bootstrap,message:`Fonti: ${bootstrapSources}`}}return visible},[providerStatus,listings,refreshedAt]);function createTracker(){if(place.trim()&&max>=min)setTrackers(p=>[{id:crypto.randomUUID(),name:place.trim(),location:place.trim(),minPrice:min,maxPrice:max,sellerType:seller,active:true,refreshHours:2},...p])}async function refreshBakeca(){setDeviceRefresh('Aggiornamento Bakeca…');try{const url=`https://torino.bakeca.it/annunci/case/luogo/bardonecchia/?hh_refresh=${Date.now()}`;const r=await fetch(url,{mode:'cors',cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const found=parseBakeca(await r.text(),min,max);setListings(prev=>[...prev.filter(x=>!x.id.startsWith('bakeca-device:')),...found]);setDeviceRefresh(found.length?`${found.length} annunci Bakeca caricati manualmente`:'Bakeca raggiungibile, ma nessun annuncio estratto con questi filtri')}catch(e){setDeviceRefresh(`Bakeca non aggiornato: ${e instanceof Error?e.message:'errore browser'}`)}}
const priceCeiling=useMemo(()=>Math.ceil(Math.max(350000,max,...listings.map(item=>item.price))/PRICE_STEP)*PRICE_STEP,[listings,max]);
const rangeStart=Math.min(100,(min/priceCeiling)*100),rangeEnd=Math.min(100,(max/priceCeiling)*100);
return <main><header><div><span className="brand">HomeHoliday</span><h1>Property Tracker</h1><p>Un solo posto per trovare, confrontare e monitorare gli immobili.</p></div><div className="pulse"><i/> {dataSource==='live'?'Dati tracker':'Modalità demo'} · {formatRefresh(refreshedAt)}</div></header><section className="tracker"><h2>Crea il tuo tracker</h2><div className="filters"><label>Luogo<input value={place} onChange={e=>setPlace(e.target.value)}/></label><label>Prezzo minimo<input type="number" value={min} onChange={e=>setMin(+e.target.value||0)}/></label><label>Prezzo massimo<input type="number" value={max} onChange={e=>setMax(+e.target.value||0)}/></label><label>Inserzionista<select value={seller} onChange={e=>setSeller(e.target.value as typeof seller)}><option>Tutti</option><option>Privato</option><option>Agenzia</option></select></label></div><button onClick={createTracker}>+ Crea Tracker</button></section>
<section className="manualRefresh"><div className="sectionTitle"><div><h2>Aggiorna manualmente</h2><p>Bakeca.it non viene aggiornato automaticamente: puoi caricare ora gli annunci disponibili.</p></div><button onClick={()=>void refreshBakeca()}>Aggiorna Bakeca.it</button></div>{deviceRefresh&&<p className="manualRefreshStatus"><b>{deviceRefresh}</b></p>}</section>
{Object.keys(visibleProviderStatus).length>0&&<section className="providers"><h2>Fonti monitorate</h2><div className="providerGrid">{Object.entries(visibleProviderStatus).map(([k,s])=><div className={`providerCard ${s.ok?'ok':'ko'}`} key={k}><span className="providerDot"/><div><b>{providerLabel(k)}</b><small>{s.ok?`${s.count??0} annunci trovati${s.message?` · ${s.message}`:''}`:s.message}</small></div></div>)}</div></section>
}<section className="stats"><div><b>{properties.length}</b><span>Immobili unici</span></div><div><b>{properties.filter(g=>g.sources.some(s=>s.status==='NEW')).length}</b><span>Nuovi</span></div><div><b>{properties.filter(g=>g.sources.length>1).length}</b><span>Su più fonti</span></div><div><b>{properties.filter(g=>g.sources.some(s=>s.sellerType==='Privato')).length}</b><span>Con privato</span></div></section>
<section><div className="sectionTitle"><div><h2>Risultati</h2><p>Risultati automatici + eventuali annunci Bakeca.it aggiornati manualmente.</p></div><div className="resultsActions"><button className="sortButton" onClick={()=>setPriceSort(current=>current==='asc'?'desc':'asc')}>{priceSort===null?'Ordina per prezzo':priceSort==='desc'?'Prezzo: dal più alto':'Prezzo: dal più basso'}</button><strong>{loading?'Aggiornamento…':`${properties.length} immobili`}</strong></div></div>
<div className="resultFilters"><div className="priceRangeFilter"><div className="filterHeading"><b>Prezzo</b><span>{money(min)} — {money(max)}</span></div><div className="dualRange"><div className="rangeTrack"/><div className="rangeSelection" style={{left:`${rangeStart}%`,right:`${100-rangeEnd}%`}}/><input aria-label="Prezzo minimo" type="range" min="0" max={priceCeiling} step={PRICE_STEP} value={min} onChange={e=>setMin(Math.min(Number(e.target.value),max-PRICE_STEP))}/><input aria-label="Prezzo massimo" type="range" min="0" max={priceCeiling} step={PRICE_STEP} value={max} onChange={e=>setMax(Math.max(Number(e.target.value),min+PRICE_STEP))}/></div></div><label className="sellerFilter">Inserzionista<select value={seller} onChange={e=>setSeller(e.target.value as typeof seller)}><option>Tutti</option><option>Privato</option><option>Agenzia</option></select></label><div className="viewFilter"><span>Visualizzazione</span><div className="viewToggle" role="group" aria-label="Visualizzazione risultati"><button className={viewMode==='cards'?'active':''} aria-pressed={viewMode==='cards'} onClick={()=>setViewMode('cards')}>Schede</button><button className={viewMode==='table'?'active':''} aria-pressed={viewMode==='table'} onClick={()=>setViewMode('table')}>Tabella</button></div></div></div>
{viewMode==='cards'?<div className="grid">{orderedProperties.map(g=>{const x=g.primary;return <article key={g.id}><div className="photo"><span className={'tag '+x.status.toLowerCase()}>{x.status}</span><span className="source">{g.sources.length>1?`${g.sources.length} fonti`:x.source}</span></div><div className="body"><small>{x.location} · {x.sellerType}</small><h3>{x.title}</h3><div className="price">{money(x.price)}</div><p>{x.sqm?`${x.sqm} m²`:''}{x.rooms?` · ${x.rooms} locali`:''}</p>{g.sources.length>1&&<div className="sourceLinks">{g.sources.map(s=><a key={s.id} href={s.sourceUrl} target="_blank" rel="noreferrer">{s.source} · {money(s.price)}</a>)}</div>}<footer>Pubblicato {formatDate(x.publishedAt)}{g.sources.length===1&&<a className="openLink" href={x.sourceUrl} target="_blank" rel="noreferrer">Apri →</a>}</footer></div></article>})}</div>:<div className="tableWrap"><table className="resultsTable"><thead><tr><th>Prezzo</th><th>Immobile</th><th>m²</th><th>Locali</th><th>Inserzionista</th><th>Fonti</th></tr></thead><tbody>{orderedProperties.map(g=>{const x=g.primary;return <tr key={g.id}><td className="tablePrice">{money(x.price)}</td><td><b>{x.title}</b><small>{x.location}</small></td><td>{x.sqm??'—'}</td><td>{x.rooms??'—'}</td><td>{x.sellerType}</td><td><div className="tableSources">{g.sources.map(s=><a key={s.id} href={s.sourceUrl} target="_blank" rel="noreferrer">{s.source}</a>)}</div></td></tr>})}</tbody></table></div>}</section>
</main>}
createRoot(document.getElementById('root')!).render(<App/>);
